FEATURE: added githooks

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,35 +1,23 @@
 #!/usr/bin/bash
 
-PASS=true
+echo "Running pre-commit script...⏳"
 
+# TODO: maybe add linters here
 
-# TODO: ADD PATTERNS FOR COMMIT MESSAGES AND BRANCH NAMES
-
-
-# STAGED_GO_FILES="$(git diff --cached --name-only | grep "^internal/" | grep ".go$")"
-
-# for FILE in $STAGED_GO_FILES; do   
-    # NOTE: here checks can be added
-# done
-
-
-if ! $PASS ; then
+# Run the tests
+if ! task test:unit; then
+    echo "Unit tests failed 🚫"
     exit 1
 fi
 
+if ! task test:integration; then
+    echo "Integration tests failed🚫"
+    exit 1
+fi
 
 # Run go mod tidy
 go mod tidy
-
 git add go.mod go.sum
 
-
-# Run go generate commands
-# go generate gen/ogen/generate.go
-# go generate gen/ent/generate.go
-
-# Add generated files to git
-# git add gen
-
-
+echo "Pre-commit checks passed!✅"
 exit 0
